### ISSUE TITLE
Add unit conversions for coordinates

### ISSUE THREAD

**Issue by pushpulldecoder** [kylecorry31/sol#63]
Currently, there is no direct way to convert geographical coordinates to different format like DDM, DMS etc.

**Comment by kylecorry31** [comment]
Hi, I plan to add this - it's currently available in my "andromeda" project (android only)

**Comment by kylecorry31** [comment]
Closing in favor of https://github.com/kylecorry31/sol/issues/28

**Comment by kylecorry31** [comment]
FYI, I've re-added coordinate formats in version 9.2.0 (removed from andromeda)
